service: portaty-coupons
app: portaty-professions
org: juvelineorb4
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  apiGateway:
    restApiId: "${self:custom.api_gateway_id.${opt:stage, self:provider.stage}}"
    restApiRootResourceId: "${self:custom.api_gateway_resourceid.${opt:stage, self:provider.stage}}"
  environment:
    TABLE_COUPON_CAMPAIGN_STREAM_ARN: "${self:custom.table_coupon_campaign_stream_arn.${opt:stage, self:provider.stage}}"
    TOPIC_SEND_NOTIFICATION: "${cf:portatyv2-${self:provider.stage}.TopicSendNotificationArn}"
    APPSYNC_URL: "${self:custom.appsync_url.${opt:stage, self:provider.stage}}"
    APPSYNC_API_KEY: "${self:custom.appsync_key.${opt:stage, self:provider.stage}}"
    OPENSE_BUSINESS_INDEX: "${self:custom.opense_business_index.${opt:stage, self:provider.stage}}"
    OPENSE_HOST: "search-portaty-opense-f2pru5qxiz73a53c7fstafplnu.us-east-1.es.amazonaws.com"
    S3_BUCKET_NAME: "${self:custom.s3_bucket_name.${opt:stage, self:provider.stage}}"

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "sns:*"
          Resource:
            - ${self:provider.environment.TOPIC_SEND_NOTIFICATION}
        - Effect: "Allow"
          Action:
            - "es:*"
          Resource:
            - arn:aws:es:us-east-1:086563672363:domain/portaty-opense/*
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource: "*"
custom:
  table_coupon_campaign_stream_arn:
    dev: "arn:aws:dynamodb:us-east-1:086563672363:table/CouponCampaign-ehid2xtqobf75gakml3qgdj45m-dev/stream/2024-11-11T16:12:10.474"
    prod: ""
  appsync_url:
    dev: "https://vkrtsagkivgqjgzbnhekkyusfm.appsync-api.us-east-1.amazonaws.com/graphql"
    prod: "https://cq6hw4g7arg4jitnxitbhihhpu.appsync-api.us-east-1.amazonaws.com/graphql"
  appsync_key:
    dev: "da2-2ardlryjrvdl3cqdyrtz2ppq5i"
    prod: "da2-x4g3fxoha5eeroeswkza7fznny"
  api_gateway_id:
    dev: "3aa3yts4zj"
    prod: "z5i64n32d6"
  api_gateway_resourceid:
    dev: "zah4kq66hf"
    prod: "xugqzpp4pb"
  opense_business_index:
    dev: "business_dev"
    prod: "business"
  s3_bucket_name:
    dev: "s3professions202858-dev"
    prod: "s3professions143312-prod"

functions:
  triggerCouponCampaign:
    handler: functions/triggerCouponCampaign.handler
    events:
      - stream:
          type: dynamodb
          arn: "${self:provider.environment.TABLE_COUPON_CAMPAIGN_STREAM_ARN}"
    layers:
      - "arn:aws:lambda:us-east-1:086563672363:layer:layer_coupons:1"
  scannerCoupon:
    handler: functions/scanner.handler
    events:
      - http:
          path: coupons/scanner
          method: post
    layers:
      - "arn:aws:lambda:us-east-1:086563672363:layer:layer_coupons:1"
  scheduleCouponsInactive:
    handler: functions/scheduleCouponsInactive.handler
    events:
      - schedule:
          rate: cron(0 0 * * ? *) # Ejecuta a medianoche UTC todos los días
          enabled: true
    layers:
      - "arn:aws:lambda:us-east-1:086563672363:layer:layer_coupons:1"
  scheduleCouponsActive:
    handler: functions/scheduleCouponsActive.handler
    events:
      - schedule:
          rate: cron(0 0 * * ? *) # Ejecuta a medianoche UTC todos los días
          enabled: true
    layers:
      - "arn:aws:lambda:us-east-1:086563672363:layer:layer_coupons:1"
  listCouponsByDistance:
    handler: functions/listCouponsByDistance.handler
    events:
      - http:
          path: coupons/listCoupons
          method: get
    layers:
      - "arn:aws:lambda:us-east-1:086563672363:layer:layer_coupons:1"
      - "arn:aws:lambda:us-east-1:086563672363:layer:opense_layer:2"
  createCoupongCampaign:
    handler: functions/createCoupongCampaign.handler
    events:
      - http:
          path: coupons/createCoupongCampaign
          method: post
    layers:
      - arn:aws:lambda:us-east-1:086563672363:layer:layer_thumbnail:2
      - arn:aws:lambda:us-east-1:086563672363:layer:openSearchBusinessSync:3
