service: portaty-dates
app: portaty-professions
org: juvelineorb4
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    TABLE_DATE_STREAM_ARN: "${self:custom.table_date_stream_arn.${opt:stage, self:provider.stage}}"
    TOPIC_SEND_NOTIFICATION: "${cf:portatyv2-${self:provider.stage}.TopicSendNotificationArn}"
    "APPSYNC_URL": "${self:custom.appsync_url.${opt:stage, self:provider.stage}}"
    "APPSYNC_API_KEY": "${self:custom.appsync_key.${opt:stage, self:provider.stage}}"

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "sns:*"
          Resource:
            - ${self:provider.environment.TOPIC_SEND_NOTIFICATION}

custom:
  table_date_stream_arn:
    dev: "arn:aws:dynamodb:us-east-1:086563672363:table/Date-ehid2xtqobf75gakml3qgdj45m-dev/stream/2024-10-17T20:02:24.390"
    prod: "arn:aws:dynamodb:us-east-1:086563672363:table/Date-3phqsjzznfdxlnjnzszwzb6rjy-prod/stream/2024-10-24T15:42:23.410"
  appsync_url:
    dev: "https://vkrtsagkivgqjgzbnhekkyusfm.appsync-api.us-east-1.amazonaws.com/graphql"
    prod: "https://cq6hw4g7arg4jitnxitbhihhpu.appsync-api.us-east-1.amazonaws.com/graphql"
  appsync_key:
    dev: "da2-2ardlryjrvdl3cqdyrtz2ppq5i"
    prod: "da2-x4g3fxoha5eeroeswkza7fznny"

functions:
  triggerDate:
    handler: functions/triggerDate.handler
    events:
      - stream:
          type: dynamodb
          arn: "${self:provider.environment.TABLE_DATE_STREAM_ARN}"
    layers:
      - "arn:aws:lambda:us-east-1:086563672363:layer:layer_dates:1"
