service: portaty-claimRequest
app: portaty-professions
org: juvelineorb4
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    TABLE_CLAIMREQUEST_STREAM_ARN: "${self:custom.table_claimRequest_stream_arn.${opt:stage, self:provider.stage}}"
    TOPIC_SEND_NOTIFICATION: "${cf:portatyv2-${self:provider.stage}.TopicSendNotificationArn}"
    APPSYNC_URL: "${self:custom.appsync_url.${opt:stage, self:provider.stage}}"
    APPSYNC_API_KEY: "${self:custom.appsync_key.${opt:stage, self:provider.stage}}"

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "sns:*"
          Resource:
            - ${self:provider.environment.TOPIC_SEND_NOTIFICATION}

custom:
  table_claimRequest_stream_arn:
    dev: "arn:aws:dynamodb:us-east-1:086563672363:table/ClaimRequest-ehid2xtqobf75gakml3qgdj45m-dev/stream/2024-10-17T20:03:13.015"
    prod: "arn:aws:dynamodb:us-east-1:086563672363:table/ClaimRequest-3phqsjzznfdxlnjnzszwzb6rjy-prod/stream/2024-10-24T15:42:34.962"
  appsync_url:
    dev: "https://vkrtsagkivgqjgzbnhekkyusfm.appsync-api.us-east-1.amazonaws.com/graphql"
    prod: "https://cq6hw4g7arg4jitnxitbhihhpu.appsync-api.us-east-1.amazonaws.com/graphql"
  appsync_key:
    dev: "da2-2ardlryjrvdl3cqdyrtz2ppq5i"
    prod: "da2-x4g3fxoha5eeroeswkza7fznny"

functions:
  triggerClaimRequest:
    handler: functions/triggerClaimRequest.handler
    events:
      - stream:
          type: dynamodb
          arn: "${self:provider.environment.TABLE_CLAIMREQUEST_STREAM_ARN}"
    layers:
      - "arn:aws:lambda:us-east-1:086563672363:layer:layer_claimRequest:1"
