org: juvelineorb4
app: portaty-professions
service: portatyv2-documentqr

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  apiGateway:
    restApiId: "${self:custom.api_gateway_id.${opt:stage, self:provider.stage}}"
    restApiRootResourceId: "${self:custom.api_gateway_resourceid.${opt:stage, self:provider.stage}}"
  environment:
    "S3_BUCKET_NAME": "${self:custom.s3_bucket_name.${opt:stage, self:provider.stage}}"
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource: "*"
custom:
  api_gateway_id:
    dev: "3aa3yts4zj"
    prod: "z5i64n32d6"
  api_gateway_resourceid:
    dev: "zah4kq66hf"
    prod: "xugqzpp4pb"
  s3_bucket_name:
    dev: "s3professions202858-dev"
    prod: "s3professions143312-prod"

functions:
  documentQr:
    handler: handler.documentQr
    events:
      - http:
          path: documentqr
          method: get
    layers:
      - arn:aws:lambda:us-east-1:086563672363:layer:documentqr_layer:1
    timeout: 30
