# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: juvelineorb4
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: portaty-professions
# "service" is the name of this project. This will also be added to your AWS resource names.
service: portaty-document
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  apiGateway:
    restApiId: "${self:custom.api_gateway_id.${opt:stage, self:provider.stage}}"
    restApiRootResourceId: "${self:custom.api_gateway_resourceid.${opt:stage, self:provider.stage}}"
  environment:
    "ARN_TABLE_BUSINESS": "${self:custom.arn_table_business.${opt:stage, self:provider.stage}}"
    "TABLE_BUSINESS_NAME": "${self:custom.table_business_name.${opt:stage, self:provider.stage}}"
    "S3_BUCKET_NAME": "${self:custom.s3_bucket_name.${opt:stage, self:provider.stage}}"
    "APPSYNC_ARN": "${self:custom.appsync_arn.${opt:stage, self:provider.stage}}"
    "APPSYNC_URL": "${self:custom.appsync_url.${opt:stage, self:provider.stage}}"
    "APPSYNC_API_KEY": "${self:custom.appsync_key.${opt:stage, self:provider.stage}}"

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "dynamodb:UpdateItem"
            - "dynamodb:GetItem"
            - "dynamodb:Query"
          Resource:
            - ${self:provider.environment.ARN_TABLE_BUSINESS}
        - Effect: "Allow"
          Action:
            - "appsync:GraphQL"
          Resource:
            - ${self:provider.environment.APPSYNC_ARN}

custom:
  arn_table_business:
    dev: "arn:aws:dynamodb:us-east-1:086563672363:table/Business-ehid2xtqobf75gakml3qgdj45m-dev"
    prod: "arn:aws:dynamodb:us-east-1:086563672363:table/Business-3phqsjzznfdxlnjnzszwzb6rjy-prod"
  table_business_name:
    dev: "Business-ehid2xtqobf75gakml3qgdj45m-dev"
    prod: "Business-3phqsjzznfdxlnjnzszwzb6rjy-prod"
  api_gateway_id:
    dev: "x0nk2m8hvi"
    prod: "z5i64n32d6"
  api_gateway_resourceid:
    dev: "eclownm620"
    prod: "xugqzpp4pb"
  s3_bucket_name:
    dev: "s3professions202858-dev"
    prod: "s3professions143312-prod"
  appsync_arn:
    dev: "arn:aws:appsync:us-east-1:086563672363:apis/ehid2xtqobf75gakml3qgdj45m/types/Mutation/fields/updateBusiness"
    prod: "arn:aws:appsync:us-east-1:086563672363:apis/3phqsjzznfdxlnjnzszwzb6rjy/types/Mutation/fields/updateBusiness"
  appsync_url:
    dev: "https://vkrtsagkivgqjgzbnhekkyusfm.appsync-api.us-east-1.amazonaws.com/graphql"
    prod: "https://cq6hw4g7arg4jitnxitbhihhpu.appsync-api.us-east-1.amazonaws.com/graphql"
  appsync_key:
    dev: "da2-2ardlryjrvdl3cqdyrtz2ppq5i"
    prod: "da2-x4g3fxoha5eeroeswkza7fznny"
functions:
  uploadCatalog:
    handler: functions/uploadCatalog.handler
    events:
      - s3:
          bucket: ${self:provider.environment.S3_BUCKET_NAME}
          event: s3:ObjectCreated:*
          existing: true
          forceDeploy: true
          rules:
            - prefix: protected/
            - suffix: .pdf
    layers:
      - arn:aws:lambda:us-east-1:086563672363:layer:layer_thumbnail:2
      - arn:aws:lambda:us-east-1:086563672363:layer:openSearchBusinessSync:3
  thumbnail:
    handler: functions/thumbnail.handler
    events:
      - http:
          path: thumbnailgenerator
          method: post
    layers:
      - arn:aws:lambda:us-east-1:086563672363:layer:layer_thumbnail:2
